---
- hosts: localhost
  connection: local
  become: true
  vars:
    localuser: badc0d3

  tasks:
  - name: install apts
    package:
      name: 
        - htop
        - tmux
        - nano
        - curl
        - terminator
        - openssh-server
        - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpeg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpeg
      owner: root
      group: root

  - name: set wallpaper
    become_user: {{localuser}}
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpeg'"

  - name: set wallpaper position
    become_user: {{localuser}}
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/{{localuser}}/.bashrc
      owner: {{localuser}}
      group: {{localuser}}

  - name: add ansible user
    user:
      name: ansibleUser
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansibleUser
      dest: /etc/sudoers.d/ansibleUser
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-update
      user: ansibleUser
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/BADC0D3/ansible_vm.git